
server:
  port: 8020

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
